services:
  - type: static
    name: math-handwriting-ai-seminar
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
